apiVersion: v1
kind: Service
metadata:
  name: review-sentinel-server
  namespace: review-sentinel
  labels:
    app.kubernetes.io/name: review-sentinel
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: review-sentinel
    app.kubernetes.io/component: server
  ports:
    - port: 80
      targetPort: 8080
